## HuyIGW04 - Linear Regression - PyTorch - M05W02

### Xem cách mà `torch.nn.Linear` hoạt động

In [95]:
from torch import nn
import torch

In [96]:
x = torch.tensor([6.7])

w = -0.34
b =  0.04

y_hat = w*x + b
print(y_hat)

tensor([-2.2380])


In [97]:
x = torch.tensor( [6.7])
y = torch.tensor([9.1])

### Khởi tạo theta có $w=-0.34$ và $b=0.04$

In [98]:
# khởi tạo theta
linear_val = nn.Linear(1, 1)


# giả định số của mình để ví dụ
linear_val.bias.data = torch.tensor([0.04])

# 2-D weight
linear_val.weight.data = torch.tensor([[-0.34]])

print(linear_val.bias)
print(linear_val.weight)

Parameter containing:
tensor([0.0400], requires_grad=True)
Parameter containing:
tensor([[-0.3400]], requires_grad=True)


In [99]:
print(linear_val.weight.shape)


torch.Size([1, 1])


In [100]:
# đã có theta, nhét x vào để tính được prediction.
y_hat = linear_val(x)
print(y_hat)

tensor([-2.2380], grad_fn=<ViewBackward0>)


### `nn.Sequential` for Linear

In [101]:
from torchsummary import summary
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(in_features=4, out_features=3),
    nn.ReLU(),
    nn.Linear(in_features=3, out_features=2)
)
model.to("cuda")
summary(model, input_size=(4,))


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [-1, 3]              15
              ReLU-2                    [-1, 3]               0
            Linear-3                    [-1, 2]               8
Total params: 23
Trainable params: 23
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


### One Sample Code  
Minh họa từng bước, sử dụng một mẫu sample duy nhất.  
  
  
<img src="image.png" alt="image" width="400"/>


In [102]:
import torch.nn as nn
import torch

# mẫu dữ liệu 1-D
x = torch.tensor([6.7])
y = torch.tensor([9.1])

# cài đặt linear - theta
linear = nn.Linear(1, 1)
linear.bias.data = torch.tensor([0.04])
linear.weight.data = torch.tensor([[-0.34]])

print(linear.bias)
print(linear.weight)

Parameter containing:
tensor([0.0400], requires_grad=True)
Parameter containing:
tensor([[-0.3400]], requires_grad=True)


In [103]:
# loss constructor
loss = nn.MSELoss()

# đưa linear - theta vào updating constructor
optimizer = torch.optim.SGD(linear.parameters(), lr=0.001)

In [ ]:
# đã chuẩn bị xong, bắt đầu quá trình training
losses = []
# compute predict
y_hat = linear(x)

# compute loss
loss_epoch = loss(y_hat, y)
losses.append(loss_epoch.item())

# compute gradient
# clear forward gradient
optimizer.zero_grad()
loss_epoch.backward()

# update weight
optimizer.step()

In [105]:
y_hat = linear(x)
loss_epoch = loss(y_hat, y)
losses.append(loss_epoch.item())

In [106]:
# kiểm tra loss xem có giảm chưa
losses

[128.5502471923828, 106.03641510009766]

### Loss đã giảm, one sample sử dụng PyTorch đã thành công. 